// Seed list of Twin Cities neighborhoods used to power the neighborhood
// tag-input's autocomplete on the submit/correct form. This is only a starting
// set of suggestions — the input lets people add their own, and any
// neighborhood already used by an existing band is merged in at runtime (see
// app/submit/page.tsx). Edit freely; order here doesn't matter (the options are
// sorted before display).

export const MINNEAPOLIS_NEIGHBORHOODS = [
  "Downtown",
  "North Loop",
  "Northeast",
  "Marcy-Holmes",
  "Dinkytown",
  "Prospect Park",
  "Como",
  "University",
  "Cedar-Riverside",
  "Elliot Park",
  "Loring Park",
  "Stevens Square",
  "Whittier",
  "Lyn-Lake",
  "Uptown",
  "East Isles",
  "Lowry Hill",
  "Lowry Hill East (The Wedge)",
  "Bryn Mawr",
  "Kenwood",
  "Cedar-Isles-Dean",
  "Linden Hills",
  "Fulton",
  "Armatage",
  "Kenny",
  "Lynnhurst",
  "Tangletown",
  "Kingfield",
  "Bryant",
  "Bancroft",
  "Central",
  "Corcoran",
  "Powderhorn Park",
  "Phillips",
  "Ventura Village",
  "Seward",
  "Longfellow",
  "Cooper",
  "Howe",
  "Hiawatha",
  "Standish",
  "Ericsson",
  "Nokomis",
  "Keewaydin",
  "Minnehaha",
  "Near North",
  "Willard-Hay",
  "Jordan",
  "Hawthorne",
  "Camden",
  "Victory",
  "Folwell",
  "Webber-Camden",
  "Audubon Park",
  "Windom Park",
  "Waite Park",
  "Columbia Park",
  "Sheridan",
  "St. Anthony West",
  "St. Anthony East",
  "Beltrami",
];

export const ST_PAUL_NEIGHBORHOODS = [
  "Downtown",
  "West Side",
  "West Seventh (Fort Road)",
  "Summit Hill",
  "Cathedral Hill",
  "Summit-University",
  "Macalester-Groveland",
  "Highland Park",
  "Merriam Park",
  "Snelling-Hamline",
  "Hamline-Midway",
  "Union Park",
  "St. Anthony Park",
  "Como",
  "North End",
  "Frogtown (Thomas-Dale)",
  "Payne-Phalen",
  "Railroad Island",
  "Dayton's Bluff",
  "Battle Creek",
  "Highwood Hills",
  "Eastview",
  "Greater East Side",
  "Hayden Heights",
  "Sun Ray",
];

// Flat, de-duplicated list of all seeded neighborhoods. Some names (e.g.
// "Downtown", "Como") exist in both cities; a Set collapses those since the
// picker keeps a single flat suggestion list regardless of the chosen city.
export const NEIGHBORHOOD_OPTIONS = Array.from(
  new Set([...MINNEAPOLIS_NEIGHBORHOODS, ...ST_PAUL_NEIGHBORHOODS]),
);
